### ISSUE TITLE
WhatsApp QR code doesn't load

### ISSUE THREAD

**Issue by yonka2019** [guyzyl/whatsapp-contact-sync#169] opened 2024-06-08 16:43 UTC

**Comment by guyzyl** [comment] 2024-06-12 10:18
Can you add some more info?
On whasync.com or locally? Has that happened once, or have you tried multiple times?

**Comment by yonka2019** [comment] 2024-06-12 10:20
on whasync, i tried multiple times, yesterday its not even loaded the QR

**Comment by guyzyl** [comment] 2024-06-12 10:24
I just tried myself and everything seems to be working.
For how long did you wait? The QR can take a few seconds to load sometimes.

**Comment by yonka2019** [comment] 2024-06-12 13:05
tested now - works good, thanks

**Comment by guyzyl** [comment] 2024-06-12 14:03
Re-opening since there's still a bug that caused this issue

**Comment by mrzcn** [comment] 2024-06-17 20:13
I have some issues.
I tried a few more times and was able to scan the QR code a few times, then started syncing, but not actually. 
Are you sure https://whasync.com/ is working?
I tried mobile and PC, not change.

**Comment by guyzyl** [comment] 2024-06-18 16:10
I just tested again and it worked for me, but that doesn't mean that everything is OK.

There are some bugs that still occur in the backed due to the WhatsApp library that is being used (whatsapp-web.js).
The problem is that its "official" development has stopped (no new release since October), but there have been changes in WhatsApp / bugs in the library that require attention.

Due to this fact, I have recently switched to a "maintained" branch of the library that is more up to date (see #164), but there are still issues with the library unfortunately.

**Comment by guyzyl** [comment] 2024-06-18 16:12
Actually, I have just checked and it seems that there has been a new official release for the library last week (first one since October).
I'll open a PR to move to it and hopefully things will work better! :)

**Comment by guyzyl** [comment] 2024-06-18 16:15
Tested locally, it causes other bugs unfortunately

**Comment by Dumonster** [comment] 2024-08-13 13:55
Having the same issue. Tried multiple browsers and incognito mode but nothing works.

**Comment by guyzyl** [comment] 2024-09-21 09:29
@Dumonster were you using whasync.com or running it locally?

**Comment by Dumonster** [comment] 2024-09-21 09:34
Hi,


I found out that it works a lot better on Firefox than on Chrome. It's nearly flawless.


Thanks!

________________________________

**Comment by guyzyl** [comment] 2024-09-21 10:13
Glad to hear!
Closing the issue now (and sorry for my delayed response)

**Closed by guyzyl** 2024-09-21 10:13 UTC
Labels: bug
