### ISSUE TITLE
 Incomplete loading of photos (blurry photos) in WhatsApp contacts sync with Google Contacts

### ISSUE THREAD

**Issue by bigplayer-ai** [guyzyl/whatsapp-contact-sync#97] opened 2023-06-27 09:33 UTC
Issue: Incomplete loading of photos in WhatsApp contacts sync with Google Contacts

Description: Occasionally, the photos of contacts in WhatsApp do not fully load, even though they are successfully synced to Google Contacts. These partially loaded photos appear blurry.

Steps to reproduce:
1. Open the WhatsApp Contact Sync website.
2. Initiate a sync process between WhatsApp and Google Contacts.
3. Observe the synced contacts in Google Contacts.
4. Note that some photos may not be completely loaded and appear blurry.

Expected behavior: All photos should be fully loaded and displayed clearly in Google Contacts after the sync process.

Additional information:
- This issue occurs intermittently and does not affect all contacts.

Please find attached any relevant error logs or screenshots for further analysis.

Please let me know if you need any further information or clarification regarding this issue.

Thank you for your attention to this matter.

**Comment by guyzyl** [comment] 2023-06-27 10:49
Thanks for opening the issue! Can you attach the screenshots + logs?
Also, I'm pretty sure this is a duplicate of #90.

**Closed** 2023-07-07 16:02 UTC
Labels: bug, duplicate
