### ISSUE TITLE
[Self hosted] When i scan the code nothing happens 

### ISSUE THREAD

**Issue by VozDeOuro** [guyzyl/whatsapp-contact-sync#22] opened 2022-11-30 06:13 UTC

**Comment by guyzyl** [comment] 2022-11-30 14:33
Can you provide more context on the issue? Do you see any errors in the console?

**Comment by VozDeOuro** [comment] 2022-11-30 17:08
sorry my fault 
the only thing that appears on the terminal is this 
![image](https://user-images.githubusercontent.com/36045463/204862439-a8d4c7c1-c886-40a9-96b9-9b828a9fbfcc.png)
i just remove some tokens

**Comment by guyzyl** [comment] 2022-11-30 17:13
I think I know what the issue is.
There's an issue where in some cases the web socket gets reconnected, and then your WhatsApp session in the backend isn't linked to the correct WS.
I was planning on deprecating the WS approach as it contains a lot of bugs, and replacing it with web hooks.
I'll try to get around to it soon and fix the underlying issue.

In the meantime, usually clearing browser cache and refreshing the page will solve the issue.

**Comment by VozDeOuro** [comment] 2022-11-30 17:22
ok thx 
i tried with 3 different browsers none of them work :|
on the mobile its keep trying read the QR code with no success

**Comment by guyzyl** [comment] 2022-11-30 17:42
That sucks, I'll try to get it fixed during the weekend.

**Comment by VozDeOuro** [comment] 2022-11-30 17:43
thx :)

**Comment by VozDeOuro** [comment] 2022-12-06 01:12
hey :) 
did you manage to take a look ?

**Comment by guyzyl** [comment] 2022-12-06 12:40
Sorry, but not yet (but haven't forgotten about it).
Hopefully sometime this week/end.

**Comment by guyzyl** [comment] 2022-12-09 04:50
@VozDeOuro I just merged a PR (#27) which should fix this bug, can you confirm it works for you now?

**Comment by VozDeOuro** [comment] 2022-12-11 03:59
hey :) 
the problems keep happening here is a screenshot from the cellphone perspective, i try to scan it but nothing happens 
the qrcode was blurry by myself 
![image](https://user-images.githubusercontent.com/36045463/206885663-f5bcb600-d899-45c4-a817-63113c5e632f.png)

**Comment by Sarveshmrao** [comment] 2022-12-11 17:16
I had this issue just now, and I solved it by just changing the background colour of the page. It worked! 
![image](https://user-images.githubusercontent.com/49156390/206918367-72c6b98b-4a54-4b91-bfad-ef4b8d9b00d3.png)
To some colour like above.

**Comment by Sarveshmrao** [comment] 2022-12-11 17:22
> @Sarveshmrao can you elaborate on what you did? To me it seems like something else caused it to function correctly.
> 
> @VozDeOuro Just so I'm sure I understood correctly, which one of these happened to you?:
> 
> * You weren't able to scan the QR with WhatsApp - you opened the WhatsApp scanner and nothing happened
> * You were able to scan the QR with WhatsApp, and the app didn't continue to the next screen

Hey @guyzyl 
I was not able to scan the code in WhatsApp or a normal QR Code Scanner. Hence I changed the background and the next second it scanned and logged me in and took me to the Google Auth step. 

I'm self hosting both Backend and Frontend FYI.

**Comment by VozDeOuro** [comment] 2022-12-11 17:28
> @Sarveshmrao can you elaborate on what you did? To me it seems like something else caused it to function correctly.
> 
> @VozDeOuro Just so I'm sure I understood correctly, which one of these happened to you?:
> - You weren't able to scan the QR with WhatsApp - you opened the WhatsApp scanner and nothing happened
> - You were able to scan the QR with WhatsApp, and the app didn't continue to the next screen

I open the WhatsApp and it's look like I'm scanning nothing, because nothing happens 

I will try that trick to change the background color

**Comment by guyzyl** [comment] 2022-12-11 17:36
@Sarveshmrao that's a very interesting solution!

Can one of you please test if adding a border to the QR fixes the issue? I'm not able to replicate it with my phone.

You can do it by adding the following block:
```css
canvas {
    border-width: 10px;
    border-color: white;
}
```

**Comment by Sarveshmrao** [comment] 2022-12-11 17:43
> @Sarveshmrao that's a very interesting solution!
> 
> Can one of you please test if adding a border to the QR fixes the issue? I'm not able to replicate it with my phone.
> You can do it by adding the following block:
> ```css
> canvas {
>     border-width: 10px;
>     border-color: white;
> }
> ```
> 

Don't add a border white. Add anything else other than black and white, as those are the colors in which the QR is generated.

**Comment by guyzyl** [comment] 2022-12-11 17:47
> > @Sarveshmrao that's a very interesting solution!
> > Can one of you please test if adding a border to the QR fixes the issue? I'm not able to replicate it with my phone.
> > You can do it by adding the following block:
> > ```css
> > canvas {
> >     border-width: 10px;
> >     border-color: white;
> > }
> > ```
> 
> Don't add a border white. Add anything else other than black and white, as those are the colors in which the QR is generated.

Good point.
Does adding a border colored at `rgb(87, 13, 248)` fix the issue? (that's the primary color of DaisyUI)

**Comment by VozDeOuro** [comment] 2022-12-12 00:13
> 

thats fixed it so the problem was with the border :)
you can close this issue if you want.

and thx for you help

**Closed** 2022-12-12 00:25 UTC

**Comment by guyzyl** [comment] 2022-12-12 00:26
@VozDeOuro Just merged the fix and closed the issue.
Thanks for reporting this bug and testing out the solution :)

**Comment by guyzyl** [comment] 2022-12-12 00:43
@VozDeOuro Sorry for bugging you, but do you mind checking the version that is now on `main`?
I tested the purple border with my phone and it didn't work.
I now changed the border color to white, and want to make sure it does the job for everyone.

**Comment by Sarveshmrao** [comment] 2022-12-12 16:00
> @VozDeOuro Sorry for bugging you, but do you mind checking the version that is now on `main`? I tested the purple border with my phone and it didn't work. I now changed the border color to white, and want to make sure it does the job for everyone.

Just checked out the new version. Yes, it works!

**Comment by guyzyl** [comment] 2022-12-12 16:05
@Sarveshmrao thanks!!!
We can leave this issue behind now :)
